# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectUI.ui',
# licensing of 'ProjectUI.ui' applies.
#
# Created: Fri Nov 22 00:36:03 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1034, 698)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(-1, 0))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 51))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SearchEventLayout = QtWidgets.QHBoxLayout()
        self.SearchEventLayout.setSpacing(2)
        self.SearchEventLayout.setObjectName("SearchEventLayout")
        self.SearchButton = QtWidgets.QPushButton(self.frame)
        self.SearchButton.setEnabled(True)
        self.SearchButton.setCursor(QtCore.Qt.ArrowCursor)
        self.SearchButton.setMouseTracking(False)
        self.SearchButton.setAutoFillBackground(False)
        self.SearchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon)
        self.SearchButton.setIconSize(QtCore.QSize(16, 16))
        self.SearchButton.setCheckable(False)
        self.SearchButton.setChecked(False)
        self.SearchButton.setAutoDefault(False)
        self.SearchButton.setDefault(False)
        self.SearchButton.setFlat(True)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchEventLayout.addWidget(self.SearchButton)
        self.searchBar = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBar.sizePolicy().hasHeightForWidth())
        self.searchBar.setSizePolicy(sizePolicy)
        self.searchBar.setMinimumSize(QtCore.QSize(50, 20))
        self.searchBar.setMaximumSize(QtCore.QSize(300, 20))
        self.searchBar.setAutoFillBackground(False)
        self.searchBar.setInputMask("")
        self.searchBar.setText("")
        self.searchBar.setFrame(True)
        self.searchBar.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.searchBar.setDragEnabled(False)
        self.searchBar.setReadOnly(False)
        self.searchBar.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.searchBar.setClearButtonEnabled(True)
        self.searchBar.setObjectName("searchBar")
        self.SearchEventLayout.addWidget(self.searchBar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SearchEventLayout.addItem(spacerItem)
        self.DarkModeButton = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DarkModeButton.sizePolicy().hasHeightForWidth())
        self.DarkModeButton.setSizePolicy(sizePolicy)
        self.DarkModeButton.setObjectName("DarkModeButton")
        self.SearchEventLayout.addWidget(self.DarkModeButton)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.SearchEventLayout.addWidget(self.toolButton)
        self.horizontalLayout_2.addLayout(self.SearchEventLayout)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(7, 64, 128);x")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 2, 1)
        self.HomeWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeWidget.sizePolicy().hasHeightForWidth())
        self.HomeWidget.setSizePolicy(sizePolicy)
        self.HomeWidget.setMouseTracking(False)
        self.HomeWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.HomeWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.HomeWidget.setIconSize(QtCore.QSize(16, 16))
        self.HomeWidget.setElideMode(QtCore.Qt.ElideRight)
        self.HomeWidget.setUsesScrollButtons(False)
        self.HomeWidget.setDocumentMode(False)
        self.HomeWidget.setTabsClosable(False)
        self.HomeWidget.setMovable(False)
        self.HomeWidget.setTabBarAutoHide(False)
        self.HomeWidget.setObjectName("HomeWidget")
        self.EventTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventTab.sizePolicy().hasHeightForWidth())
        self.EventTab.setSizePolicy(sizePolicy)
        self.EventTab.setObjectName("EventTab")
        self.gridLayout = QtWidgets.QGridLayout(self.EventTab)
        self.gridLayout.setObjectName("gridLayout")
        self.EventsWidget = QtWidgets.QTabWidget(self.EventTab)
        self.EventsWidget.setEnabled(True)
        self.EventsWidget.setCursor(QtCore.Qt.ArrowCursor)
        self.EventsWidget.setAutoFillBackground(False)
        self.EventsWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.EventsWidget.setUsesScrollButtons(True)
        self.EventsWidget.setObjectName("EventsWidget")
        self.AllEventsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AllEventsTab.sizePolicy().hasHeightForWidth())
        self.AllEventsTab.setSizePolicy(sizePolicy)
        self.AllEventsTab.setObjectName("AllEventsTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.AllEventsTab)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.AllEventsTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 810, 466))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        #self.label.setObjectName("label")
        #self.verticalLayout_2.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.EventsWidget.addTab(self.AllEventsTab, "")
        self.FavoritesEventsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FavoritesEventsTab.sizePolicy().hasHeightForWidth())
        self.FavoritesEventsTab.setSizePolicy(sizePolicy)
        self.FavoritesEventsTab.setObjectName("FavoritesEventsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.FavoritesEventsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.FavoritesEventsTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 809, 469))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        #self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        #self.label_2.setObjectName("label_2")
        #self.verticalLayout.addWidget(self.label_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.EventsWidget.addTab(self.FavoritesEventsTab, "")
        self.gridLayout.addWidget(self.EventsWidget, 0, 0, 1, 1)
        self.HomeWidget.addTab(self.EventTab, "")
        self.CalendarTab = QtWidgets.QWidget()
        self.CalendarTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalendarTab.sizePolicy().hasHeightForWidth())
        self.CalendarTab.setSizePolicy(sizePolicy)
        self.CalendarTab.setObjectName("CalendarTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.CalendarTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.CalendarTab)
        self.textBrowser_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_2.setUndoRedoEnabled(True)
        self.textBrowser_2.setOverwriteMode(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_6.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        #self.AddEventsCalndar = QtWidgets.QPushButton(self.CalendarTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.AddEventsCalndar.sizePolicy().hasHeightForWidth())
        #self.AddEventsCalndar.setSizePolicy(sizePolicy)
        #self.AddEventsCalndar.setAutoDefault(False)
        #self.AddEventsCalndar.setDefault(False)
       # self.AddEventsCalndar.setObjectName("AddEventsCalndar")
        #self.horizontalLayout.addWidget(self.AddEventsCalndar)
        self.PrintEventsCalendar = QtWidgets.QPushButton(self.CalendarTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrintEventsCalendar.sizePolicy().hasHeightForWidth())
        self.PrintEventsCalendar.setSizePolicy(sizePolicy)
        self.PrintEventsCalendar.setAutoDefault(False)
        self.PrintEventsCalendar.setObjectName("PrintEventsCalendar")
        self.horizontalLayout.addWidget(self.PrintEventsCalendar)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.HomeWidget.addTab(self.CalendarTab, "")
        self.gridLayout_2.addWidget(self.HomeWidget, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setWhatsThis("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.HomeWidget.setCurrentIndex(0)
        self.EventsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.searchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "    Search for events", None, -1))
        self.DarkModeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Dark Mode", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
#        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.EventsWidget.setTabText(self.EventsWidget.indexOf(self.AllEventsTab), QtWidgets.QApplication.translate("MainWindow", "All Events", None, -1))
       # self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.EventsWidget.setTabText(self.EventsWidget.indexOf(self.FavoritesEventsTab), QtWidgets.QApplication.translate("MainWindow", "Favorites Events", None, -1))
        self.HomeWidget.setTabText(self.HomeWidget.indexOf(self.EventTab), QtWidgets.QApplication.translate("MainWindow", "Events", None, -1))
        #self.AddEventsCalndar.setText(QtWidgets.QApplication.translate("MainWindow", "Add Events", None, -1))
        self.PrintEventsCalendar.setText(QtWidgets.QApplication.translate("MainWindow", "Print Events", None, -1))
        self.HomeWidget.setTabText(self.HomeWidget.indexOf(self.CalendarTab), QtWidgets.QApplication.translate("MainWindow", "Calendar", None, -1))
        self.menufile.setTitle(QtWidgets.QApplication.translate("MainWindow", "file", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))

import imagesUI_qrc
