# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectUI.ui',
# licensing of 'ProjectUI.ui' applies.
#
# Created: Mon Nov 18 23:11:23 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1038, 692)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(-1, 0))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 51))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SearchEventLayout = QtWidgets.QHBoxLayout()
        self.SearchEventLayout.setSpacing(2)
        self.SearchEventLayout.setObjectName("SearchEventLayout")
        self.SearchButton = QtWidgets.QPushButton(self.frame)
        self.SearchButton.setEnabled(True)
        self.SearchButton.setCursor(QtCore.Qt.ArrowCursor)
        self.SearchButton.setMouseTracking(False)
        self.SearchButton.setAutoFillBackground(False)
        self.SearchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon)
        self.SearchButton.setIconSize(QtCore.QSize(16, 16))
        self.SearchButton.setCheckable(False)
        self.SearchButton.setChecked(False)
        self.SearchButton.setAutoDefault(False)
        self.SearchButton.setDefault(False)
        self.SearchButton.setFlat(True)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchEventLayout.addWidget(self.SearchButton)
        self.searchBar = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBar.sizePolicy().hasHeightForWidth())
        self.searchBar.setSizePolicy(sizePolicy)
        self.searchBar.setMinimumSize(QtCore.QSize(50, 20))
        self.searchBar.setMaximumSize(QtCore.QSize(300, 20))
        self.searchBar.setAutoFillBackground(False)
        self.searchBar.setInputMask("")
        self.searchBar.setText("")
        self.searchBar.setFrame(True)
        self.searchBar.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.searchBar.setDragEnabled(False)
        self.searchBar.setReadOnly(False)
        self.searchBar.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.searchBar.setClearButtonEnabled(True)
        self.searchBar.setObjectName("searchBar")
        self.SearchEventLayout.addWidget(self.searchBar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SearchEventLayout.addItem(spacerItem)
        self.DarkModeButton = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DarkModeButton.sizePolicy().hasHeightForWidth())
        self.DarkModeButton.setSizePolicy(sizePolicy)
        self.DarkModeButton.setObjectName("DarkModeButton")
        self.SearchEventLayout.addWidget(self.DarkModeButton)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.SearchEventLayout.addWidget(self.toolButton)
        self.horizontalLayout_2.addLayout(self.SearchEventLayout)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(7, 64, 128);x")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 2, 1)
        self.HomeWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeWidget.sizePolicy().hasHeightForWidth())
        self.HomeWidget.setSizePolicy(sizePolicy)
        self.HomeWidget.setMouseTracking(False)
        self.HomeWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.HomeWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.HomeWidget.setIconSize(QtCore.QSize(16, 16))
        self.HomeWidget.setElideMode(QtCore.Qt.ElideRight)
        self.HomeWidget.setUsesScrollButtons(False)
        self.HomeWidget.setDocumentMode(False)
        self.HomeWidget.setTabsClosable(False)
        self.HomeWidget.setMovable(False)
        self.HomeWidget.setTabBarAutoHide(False)
        self.HomeWidget.setObjectName("HomeWidget")
        self.EventTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventTab.sizePolicy().hasHeightForWidth())
        self.EventTab.setSizePolicy(sizePolicy)
        self.EventTab.setObjectName("EventTab")
        self.gridLayout = QtWidgets.QGridLayout(self.EventTab)
        self.gridLayout.setObjectName("gridLayout")
        self.EventsWidget = QtWidgets.QTabWidget(self.EventTab)
        self.EventsWidget.setEnabled(True)
        self.EventsWidget.setCursor(QtCore.Qt.ArrowCursor)
        self.EventsWidget.setAutoFillBackground(False)
        self.EventsWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.EventsWidget.setUsesScrollButtons(True)
        self.EventsWidget.setObjectName("EventsWidget")
        self.AllEventsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AllEventsTab.sizePolicy().hasHeightForWidth())
        self.AllEventsTab.setSizePolicy(sizePolicy)
        self.AllEventsTab.setObjectName("AllEventsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.AllEventsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.AllEventsTab)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(114)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(19)
        self.gridLayout_8.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.EventsWidget.addTab(self.AllEventsTab, "")
        self.MyEventsTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyEventsTab.sizePolicy().hasHeightForWidth())
        self.MyEventsTab.setSizePolicy(sizePolicy)
        self.MyEventsTab.setObjectName("MyEventsTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.MyEventsTab)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.MyEventsTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 814, 460))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        #self.label.setObjectName("label")
        #self.verticalLayout_2.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.EventsWidget.addTab(self.MyEventsTab, "")
        self.gridLayout.addWidget(self.EventsWidget, 0, 0, 1, 1)
        self.HomeWidget.addTab(self.EventTab, "")
        self.CalendarTab = QtWidgets.QWidget()
        self.CalendarTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalendarTab.sizePolicy().hasHeightForWidth())
        self.CalendarTab.setSizePolicy(sizePolicy)
        self.CalendarTab.setObjectName("CalendarTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.CalendarTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.CalendarTab)
        self.textBrowser_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_2.setUndoRedoEnabled(True)
        self.textBrowser_2.setOverwriteMode(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_6.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddEventsCalndar = QtWidgets.QPushButton(self.CalendarTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEventsCalndar.sizePolicy().hasHeightForWidth())
        self.AddEventsCalndar.setSizePolicy(sizePolicy)
        self.AddEventsCalndar.setAutoDefault(False)
        self.AddEventsCalndar.setDefault(False)
        self.AddEventsCalndar.setObjectName("AddEventsCalndar")
        self.horizontalLayout.addWidget(self.AddEventsCalndar)
        self.PrintEventsCalendar = QtWidgets.QPushButton(self.CalendarTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrintEventsCalendar.sizePolicy().hasHeightForWidth())
        self.PrintEventsCalendar.setSizePolicy(sizePolicy)
        self.PrintEventsCalendar.setAutoDefault(False)
        self.PrintEventsCalendar.setObjectName("PrintEventsCalendar")
        self.horizontalLayout.addWidget(self.PrintEventsCalendar)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.HomeWidget.addTab(self.CalendarTab, "")
        self.gridLayout_2.addWidget(self.HomeWidget, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setWhatsThis("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.popup = QtWidgets.QMessageBox()

        self.retranslateUi(MainWindow)
        self.HomeWidget.setCurrentIndex(0)
        self.EventsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.searchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "    Search for events", None, -1))
        self.DarkModeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Dark Mode", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(10).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(11).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(12).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(13).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(14).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(15).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(16).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(17).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(18).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(19).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(20).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(21).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(22).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.verticalHeaderItem(23).setText(QtWidgets.QApplication.translate("MainWindow", "New Row", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "#", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Category", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Event Name", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Description", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Price", None, -1))
        self.tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.tableWidget.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Time", None, -1))
        self.tableWidget.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Location", None, -1))
        self.tableWidget.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "New Column", None, -1))
        self.tableWidget.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "New Column", None, -1))
        self.tableWidget.horizontalHeaderItem(10).setText(QtWidgets.QApplication.translate("MainWindow", "New Column", None, -1))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 2).setText(QtWidgets.QApplication.translate("MainWindow", "jgvgjkjkjkkjkjkjkjkjjkjkkjjkjkjkjkjkjkjkjkjk", None, -1))
        self.tableWidget.item(1, 2).setText(QtWidgets.QApplication.translate("MainWindow", "ghhgh", None, -1))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.EventsWidget.setTabText(self.EventsWidget.indexOf(self.AllEventsTab), QtWidgets.QApplication.translate("MainWindow", "All Events", None, -1))
        #self.label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.EventsWidget.setTabText(self.EventsWidget.indexOf(self.MyEventsTab), QtWidgets.QApplication.translate("MainWindow", "My Events", None, -1))
        self.HomeWidget.setTabText(self.HomeWidget.indexOf(self.EventTab), QtWidgets.QApplication.translate("MainWindow", "Events", None, -1))
        self.AddEventsCalndar.setText(QtWidgets.QApplication.translate("MainWindow", "Add Events", None, -1))
        self.PrintEventsCalendar.setText(QtWidgets.QApplication.translate("MainWindow", "Print Events", None, -1))
        self.HomeWidget.setTabText(self.HomeWidget.indexOf(self.CalendarTab), QtWidgets.QApplication.translate("MainWindow", "Calendar", None, -1))
        self.menufile.setTitle(QtWidgets.QApplication.translate("MainWindow", "file", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))

import imagesUI_qrc
